on: [push]

name: Rust Rsync 


jobs:
  linux_build_and_test:
    strategy:
      fail-fast: false # Don't cancel other matrix jobs if one fails
      matrix:
        cfg:
        - { name: ArmV7,   target: armv7-unknown-linux-gnueabihf, cross: true }
        - { name: Amd64,  target: x86_64-unknown-linux-gnu, cross: false }
       #- { name: PowerPC64,  target: powerpc64-unknown-linux-gnu, cross: false }
        
    name: "Rust Rsync Linux ${{matrix.cfg.name}}"
    runs-on: ubuntu-20.04 
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{matrix.cfg.target}}
          override:  ${{matrix.cfg.cross}}
      - uses: actions-rs/cargo@v1
        with:
          use-cross: ${{matrix.cfg.cross}}
          command: build
          args: --release --all-features --target=${{ matrix.cfg.target }}